# Generated by Django 5.0.4 on 2024-04-16 14:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('merchant', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Channel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('website_url', models.URLField(max_length=254)),
                ('trendyol_url', models.URLField(max_length=254)),
                ('amazon_url', models.URLField(max_length=254)),
                ('application', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='merchant.application')),
            ],
        ),
    ]
